// <auto-generated />
namespace Lifesys.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Documento_Numero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Documento_Numero));
        
        string IMigrationMetadata.Id
        {
            get { return "202002062155264_Documento_Numero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
