// <auto-generated />
namespace Lifesys.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CargaInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CargaInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202002050240231_CargaInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
